// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1RPr5v6eVdmm1g6dAIJn3r0ehUgPG5o8',
    appId: '1:380380307183:web:9a13cbbc0974776ba6c51a',
    messagingSenderId: '380380307183',
    projectId: 'fb-ee47f',
    authDomain: 'fb-ee47f.firebaseapp.com',
    storageBucket: 'fb-ee47f.firebasestorage.app',
    measurementId: 'G-WFXNFM85G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq2k85b2mU65YcuGRVzQKS3PaXO92xzUA',
    appId: '1:380380307183:android:70549087120e5025a6c51a',
    messagingSenderId: '380380307183',
    projectId: 'fb-ee47f',
    storageBucket: 'fb-ee47f.firebasestorage.app',
  );
}
